change yarn to bun.

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -26,7 +26,7 @@ command -v pod >/dev/null 2>&1 || {
 }
 
 # Ensure Node.js is installed
-command -v npm >/dev/null 2>&1 || {
+command -v node >/dev/null 2>&1 || {
   echo "This app requires Node.js to run, but it was not found on your system."
   echo "Installing node with brew..."
   brew install node
@@ -39,18 +39,11 @@ command -v watchman >/dev/null 2>&1 || {
   brew install watchman
 }
 
-# Ensure Yarn is installed
-command -v yarn >/dev/null 2>&1 || {
-  echo "This app requires Yarn package manager, but it was not found on your system."
-  echo "Installing yarn with brew..."
-  brew install yarn
-}
-
-# Ensure react-native-cli is installed
-command -v react-native >/dev/null 2>&1 || {
-  echo "This app requires react-native-cli, but it was not found on your system."
-  echo "Installing react-native-cli globally with yarn..."
-  yarn global add react-native-cli
+# Ensure Bun is installed
+command -v bun >/dev/null 2>&1 || {
+  echo "This app requires Bun, but it was not found on your system."
+  echo "Installing bun with brew..."
+  brew install bun
 }
 
 # IF NEEDED: Ensure appleSimUtils is installed
@@ -63,9 +56,9 @@ command -v react-native >/dev/null 2>&1 || {
 
 # IF NEEDED: Ensure detox-cli is installed
 # command -v detox >/dev/null 2>&1 || {
-#   echo "This app requires detox-cli to run end to end tests, but it was not found on your system."
-#   echo "Installing detox globally with npm..."
-#   npm install -g detox-cli
+#   echo "This app requires detox to run end to end tests, but it was not found on your system."
+#   echo "Installing detox with bunx..."
+#   bunx detox --help
 # }
 
 # IF NEEDED: Ensure phraseapp is installed
@@ -77,10 +70,10 @@ command -v react-native >/dev/null 2>&1 || {
 # }
 
 echo "----------------------------------------------------------"
-echo "Installing NPM Packages with Yarn"
+echo "Installing packages with Bun"
 echo "----------------------------------------------------------"
 
-yarn || { echo "NPM Packages could not be installed!"; exit 1; };
+bun install || { echo "Packages could not be installed!"; exit 1; };
 
 echo "----------------------------------------------------------"
 echo "Installing CocoaPods"
@@ -102,11 +95,11 @@ echo "----------------------------------------------------------"
 echo "Running tests to verify setup is complete"
 echo "----------------------------------------------------------"
 
-yarn test || { exit 1; }
+bun test || { exit 1; }
 
 echo "----------------------------------------------------------"
 echo "Setup complete!"
 echo "----------------------------------------------------------"
 
 echo "To run the app on iOS:"
-echo "react-native run-ios"
+echo "bunx react-native run-ios"
